# Generated by Django 5.1.10 on 2026-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
