# Generated by Django 5.1.10 on 2026-10-01 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(db_index=True)),
                ('navratri_day', models.PositiveSmallIntegerField()),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_given', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='participants.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'distribution_date'), name='uniq_claim_per_participant_per_day')],
            },
        ),
    ]
