# Generated by Django 5.1.10 on 2026-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('phone_normalized', models.CharField(db_index=True, max_length=10)),
                ('photo', models.ImageField(upload_to='participants/')),
                ('extra_identifier', models.CharField(blank=True, max_length=60)),
                ('qr_token_hash', models.CharField(max_length=64, unique=True)),
                ('qr_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('qr_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
